export type Language = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW';
export type Tab = 'search' | 'map' | 'plan' | 'signals';
export type Category = 'all' | 'culture' | 'food' | 'local';

export type LocalizedText = Partial<Record<Language, string>> & {
  ko: string;
  en: string;
};

export interface Place {
  id: string;
  name: LocalizedText;
  region: LocalizedText;
  category: Exclude<Category, 'all'>;
  distanceKm: number;
  image: string;
  reason: LocalizedText;
  source: LocalizedText;
  dataAsOf: LocalizedText;
  weather: LocalizedText;
  docent: LocalizedText;
  position: { left: string; top: string };
}

export const languages: Array<{ value: Language; label: string }> = [
  { value: 'ko', label: '한국어' },
  { value: 'en', label: 'English' },
  { value: 'ja', label: '日本語' },
  { value: 'zh-CN', label: '简体中文' },
  { value: 'zh-TW', label: '繁體中文' },
];

export const regionLabels: Record<string, LocalizedText> = {
  '서울 종로구': { ko: '서울 종로구', en: 'Jongno-gu, Seoul' },
  '부산 중구': { ko: '부산 중구', en: 'Jung-gu, Busan' },
  '대구 중구': { ko: '대구 중구', en: 'Jung-gu, Daegu' },
  '인천 중구': { ko: '인천 중구', en: 'Jung-gu, Incheon' },
  '광주 동구': { ko: '광주 동구', en: 'Dong-gu, Gwangju' },
  '대전 중구': { ko: '대전 중구', en: 'Jung-gu, Daejeon' },
  '울산 중구': { ko: '울산 중구', en: 'Jung-gu, Ulsan' },
  세종시: { ko: '세종시', en: 'Sejong City' },
  '경기 수원시': { ko: '경기 수원시', en: 'Suwon, Gyeonggi' },
  '강원 강릉시': { ko: '강원 강릉시', en: 'Gangneung, Gangwon' },
  '충북 청주시': { ko: '충북 청주시', en: 'Cheongju, Chungbuk' },
  '충남 천안시': { ko: '충남 천안시', en: 'Cheonan, Chungnam' },
  '전북 전주시 완산구': { ko: '전북 전주시 완산구', en: 'Wansan-gu, Jeonju' },
  '전남 여수시': { ko: '전남 여수시', en: 'Yeosu, Jeonnam' },
  '경북 경주시': { ko: '경북 경주시', en: 'Gyeongju, Gyeongbuk' },
  '경남 창원시': { ko: '경남 창원시', en: 'Changwon, Gyeongnam' },
  '제주 제주시': { ko: '제주 제주시', en: 'Jeju City' },
};

export const regions = Object.keys(regionLabels);

export const places: Place[] = [
  {
    id: 'gyeongbokgung',
    name: { ko: '경복궁', en: 'Gyeongbokgung Palace' },
    region: { ko: '서울 종로구', en: 'Jongno-gu, Seoul' },
    category: 'culture',
    distanceKm: 1.2,
    image: './assets/palace.jpg',
    reason: {
      ko: '오후 햇빛과 낮은 혼잡도가 겹치는 시간이에요.',
      en: 'Afternoon light and lower crowd levels align right now.',
    },
    source: { ko: '공식 장소 데모 스냅샷', en: 'Demo official-place snapshot' },
    dataAsOf: { ko: '데모 시드 · 5분 전', en: 'Demo seed · 5 min ago' },
    weather: { ko: '24°C · 야외 활동 무난', en: '24°C · Good for outdoors' },
    docent: {
      ko: '경복궁은 조선 왕조의 중심 궁궐입니다. 근정전으로 향하며 지붕의 곡선과 마당의 축을 함께 살펴보세요.',
      en: 'Gyeongbokgung was the central palace of the Joseon dynasty. Notice how the courtyard axis frames Geunjeongjeon.',
    },
    position: { left: '31%', top: '42%' },
  },
  {
    id: 'gwangjang',
    name: { ko: '광장시장', en: 'Gwangjang Market' },
    region: { ko: '서울 종로구', en: 'Jongno-gu, Seoul' },
    category: 'food',
    distanceKm: 0.8,
    image: './assets/market.jpg',
    reason: {
      ko: '시장 동선과 점심 시간을 함께 맞추기 좋아요.',
      en: 'The market route fits a compact lunch stop.',
    },
    source: { ko: '공식 장소 데모 스냅샷', en: 'Demo official-place snapshot' },
    dataAsOf: { ko: '데모 시드 · 12분 전', en: 'Demo seed · 12 min ago' },
    weather: { ko: '24°C · 실내외 혼합', en: '24°C · Indoor and outdoor' },
    docent: {
      ko: '광장시장은 먹거리뿐 아니라 원단과 생활 문화가 함께 이어지는 시장입니다. 중앙 통로와 골목의 분위기 차이를 느껴보세요.',
      en: 'Gwangjang Market connects food, textiles, and everyday culture. Compare the main aisle with the smaller side lanes.',
    },
    position: { left: '67%', top: '55%' },
  },
  {
    id: 'modern-art',
    name: { ko: '국립현대미술관 서울', en: 'MMCA Seoul' },
    region: { ko: '서울 종로구', en: 'Jongno-gu, Seoul' },
    category: 'culture',
    distanceKm: 1.5,
    image: './assets/museum.jpg',
    reason: {
      ko: '소나기 예보가 있어 실내 대체 장소로 적합해요.',
      en: 'A practical indoor alternative while showers pass.',
    },
    source: { ko: '공식 장소 데모 스냅샷', en: 'Demo official-place snapshot' },
    dataAsOf: { ko: '데모 시드 · 10분 전', en: 'Demo seed · 10 min ago' },
    weather: { ko: '22°C · 실내 추천', en: '22°C · Indoor recommended' },
    docent: {
      ko: '이 미술관은 한국 근현대 미술의 흐름을 다양한 매체로 보여줍니다. 작품 사이의 빛과 공간 구성도 함께 관찰해보세요.',
      en: 'The museum traces Korean modern and contemporary art across media. Pay attention to how light and space connect the works.',
    },
    position: { left: '49%', top: '31%' },
  },
  {
    id: 'botanica',
    name: { ko: '보타니카 카페', en: 'Botanica Cafe' },
    region: { ko: '서울 종로구', en: 'Jongno-gu, Seoul' },
    category: 'local',
    distanceKm: 2.1,
    image: './assets/botanical-cafe.jpg',
    reason: {
      ko: '광고성 언급을 제외한 최근 집계에서 조용한 공간으로 분류됐어요.',
      en: 'Recent governed mentions classify it as a quieter local stop.',
    },
    source: { ko: '관리형 집계 데모', en: 'Demo governed aggregate' },
    dataAsOf: { ko: '데모 시드 · 20분 전', en: 'Demo seed · 20 min ago' },
    weather: { ko: '23°C · 실내', en: '23°C · Indoors' },
    docent: {
      ko: '식물과 자연광이 어우러진 작은 휴식 공간입니다. 긴 관광 동선 사이에 잠시 머물기 좋아요.',
      en: 'A small pause point shaped by plants and natural light, useful between longer walking segments.',
    },
    position: { left: '76%', top: '27%' },
  },
];

export const uiCopy: Record<Language, Record<string, string>> = {
  ko: {
    search: '검색', map: '지도', plan: '일정', signals: '로컬 신호',
    demoData: '데모 데이터', currentRegion: '현재 지역', change: '변경',
    all: '전체', culture: '문화', food: '맛집', local: '로컬',
    tripTitle: '어떤 여행을 계획 중인가요?', tripBody: '지금의 여행 방식에 가장 가까운 항목을 골라주세요.',
    spontaneous: '즉흥 여행', planned: '계획 여행', localFocused: '찐 로컬 중심', next: '다음',
    languageTitle: '표시 언어를 선택해주세요', languageBody: '앱의 주요 화면이 선택한 언어로 바뀝니다.',
    locationTitle: '추천 기준 지역을 정해주세요', locationBody: '위치 권한 없이도 전국 지역을 직접 선택할 수 있어요.',
    currentLocation: '현재 위치 사용', manualRegion: '지역 직접 선택', start: 'LALA 시작하기',
    searchPlaceholder: '장소나 지역을 검색하세요', distance: '거리순', popular: '추천순',
    recent: '최근 검색', evidence: '추천 근거', updated: '데이터 시각', source: '출처',
    addPlan: '일정에 추가', saved: '저장됨', save: '저장', route: '경로 보기',
    docent: 'AI 도슨트', textMode: '텍스트 모드', audioUnavailable: '음성은 데모에서 비활성화됨',
    generateWithGemini: 'Gemini로 새 도슨트 만들기', checkingGemini: '서버 설정 확인 중', generatingDocent: '근거를 바탕으로 작성 중',
    liveDocentReady: '서버에서 생성한 도슨트', liveDocentUnavailable: '서버 Secret이 없어 기본 도슨트를 보여드려요.',
    morning: '오전', lunch: '점심', afternoon: '오후', evening: '저녁', estimated: '예상',
    intervention: '현재 지역에 소나기 예보가 있어 실내 대체 장소를 제안합니다.',
    keepPlan: '기존 일정 유지', applyAlternative: '대체 장소 적용', undo: '되돌리기',
    signalTitle: '광고성 언급을 걸러낸 최근 로컬 분위기', signalDisclosure: '원문·작성자·외부 URL 없이 집계 결과만 표시하는 데모입니다.',
    viewPlace: '장소 보기', noResults: '검색 결과가 없습니다', reset: '데모 초기화', settings: '설정', close: '닫기',
    notifications: '알림', mainNavigation: '주요 메뉴', categoryFilter: '카테고리 필터',
    mapAlt: '서울 종로구 데모 지도 배경', pmModerate: '미세먼지 데모: 보통', details: '상세 보기',
    clearSearch: '검색어 지우기', sortResults: '검색 결과 정렬', explore: '둘러보기',
    forecastContext: '지역 신호 · 데모 날씨', fourSlotRhythm: '4슬롯 여행 리듬',
    openSlot: '비어 있는 슬롯', noCandidate: '후보가 없을 때 장소를 임의로 만들지 않습니다.',
    governedAggregate: '관리형 집계', quiet: '한적함', active: '활기참', organic: '자연 언급',
    filteredNote: '광고성·중복 언급을 제외했습니다.', privacyNote: '원문과 작성자 정보는 노출하지 않습니다.',
    textFirst: '텍스트 우선 대체 경로', transparentEvidence: '투명한 근거', reason: '추천 사유', gallery: '갤러리',
    languageLabel: '언어', regionLabel: '지역', evidenceFirst: '근거 우선 데모',
    demoBoundaryNote: '결정 가능한 데모 시드 데이터만 사용하며 실제 LALA 운영 결과로 주장하지 않습니다.',
    noLocationPermission: '데모에서는 실제 위치 권한을 요청하지 않으며 서울 종로구 데모 지역으로 시작합니다.',
    back: '이전', coverageUnavailable: '이 지역의 데모 데이터는 아직 준비되지 않았습니다.',
    coverageBody: '전국 지역 선택 흐름은 사용할 수 있지만, 다른 지역의 장소를 서울 데이터로 대신 보여주지 않습니다.',
    chooseDemoRegion: '서울 종로구 데모 보기',
  },
  en: {
    search: 'Search', map: 'Map', plan: 'Plan', signals: 'Local Signals',
    demoData: 'Demo data', currentRegion: 'Current region', change: 'Change',
    all: 'All', culture: 'Culture', food: 'Food', local: 'Local',
    tripTitle: 'What kind of trip are you planning?', tripBody: 'Choose the option closest to how you want to explore today.',
    spontaneous: 'Spontaneous', planned: 'Planned', localFocused: 'Local-focused', next: 'Next',
    languageTitle: 'Choose your display language', languageBody: 'Primary app navigation will use your selected language.',
    locationTitle: 'Set your recommendation region', locationBody: 'You can select a nationwide region without location permission.',
    currentLocation: 'Use current location', manualRegion: 'Choose a region', start: 'Start LALA',
    searchPlaceholder: 'Search places or regions', distance: 'Distance', popular: 'Recommended',
    recent: 'Recent searches', evidence: 'Why this place', updated: 'Data time', source: 'Source',
    addPlan: 'Add to plan', saved: 'Saved', save: 'Save', route: 'View route',
    docent: 'AI docent', textMode: 'Text mode', audioUnavailable: 'Audio is disabled in this demo',
    generateWithGemini: 'Generate with Gemini', checkingGemini: 'Checking server setup', generatingDocent: 'Writing from the evidence',
    liveDocentReady: 'Server-generated docent', liveDocentUnavailable: 'The server secret is unavailable, so the default docent remains.',
    morning: 'Morning', lunch: 'Lunch', afternoon: 'Afternoon', evening: 'Evening', estimated: 'Estimated',
    intervention: 'Showers are forecast in this region, so we suggest a nearby indoor alternative.',
    keepPlan: 'Keep current plan', applyAlternative: 'Use alternative', undo: 'Undo',
    signalTitle: 'Recent local context with commercial mentions filtered', signalDisclosure: 'This demo shows aggregate results without raw text, authors, or external URLs.',
    viewPlace: 'View place', noResults: 'No results found', reset: 'Reset demo', settings: 'Settings', close: 'Close',
    notifications: 'Notifications', mainNavigation: 'Main navigation', categoryFilter: 'Category filter',
    mapAlt: 'Demo map background of Jongno-gu, Seoul', pmModerate: 'PM10 demo: Moderate', details: 'View details',
    clearSearch: 'Clear search', sortResults: 'Sort results', explore: 'Explore',
    forecastContext: 'Local signal · Demo weather', fourSlotRhythm: 'Four-slot travel rhythm',
    openSlot: 'Open slot', noCandidate: 'No place is invented when candidates are unavailable.',
    governedAggregate: 'Governed aggregate', quiet: 'Quiet', active: 'Active', organic: 'organic mentions',
    filteredNote: 'Commercial and duplicate mentions are filtered.', privacyNote: 'Raw text and author identity are not exposed.',
    textFirst: 'Text-first fallback', transparentEvidence: 'Transparent evidence', reason: 'Reason', gallery: 'Gallery',
    languageLabel: 'Language', regionLabel: 'Region', evidenceFirst: 'Evidence-first demo',
    demoBoundaryNote: 'This repository uses deterministic demo seed data and does not claim live LALA runtime evidence.',
    noLocationPermission: 'This demo does not request real location permission and starts from the Jongno-gu demo region.',
    back: 'Back', coverageUnavailable: 'Demo data is not available for this region yet.',
    coverageBody: 'Nationwide region selection works, but we never substitute Seoul places for another region.',
    chooseDemoRegion: 'View the Jongno-gu demo',
  },
  ja: {
    search: '検索', map: '地図', plan: '日程', signals: 'ローカル情報',
    demoData: 'デモデータ', currentRegion: '現在の地域', change: '変更',
    all: 'すべて', culture: '文化', food: 'グルメ', local: 'ローカル',
    tripTitle: 'どんな旅を計画していますか？', tripBody: '今日の旅に一番近いスタイルを選んでください。',
    spontaneous: '気ままな旅', planned: '計画的な旅', localFocused: 'ローカル中心', next: '次へ',
    languageTitle: '表示言語を選択', languageBody: '主要な画面が選択した言語に変わります。',
    locationTitle: 'おすすめ地域を設定', locationBody: '位置情報を許可せず、地域を直接選べます。',
    currentLocation: '現在地を使用', manualRegion: '地域を選択', start: 'LALAを始める',
    searchPlaceholder: '場所や地域を検索', distance: '距離順', popular: 'おすすめ順',
    recent: '最近の検索', evidence: 'おすすめの理由', updated: 'データ時刻', source: '出典',
    addPlan: '日程に追加', saved: '保存済み', save: '保存', route: 'ルートを見る',
    docent: 'AIガイド', textMode: 'テキスト', audioUnavailable: '音声はデモでは無効です',
    generateWithGemini: 'Geminiでガイドを作成', checkingGemini: 'サーバー設定を確認中', generatingDocent: '根拠をもとに作成中',
    liveDocentReady: 'サーバー生成ガイド', liveDocentUnavailable: 'サーバーSecretがないため、標準ガイドを表示します。',
    morning: '午前', lunch: '昼', afternoon: '午後', evening: '夜', estimated: '推定',
    intervention: 'この地域では雨が予想されるため、屋内の代替場所を提案します。',
    keepPlan: '元の日程を維持', applyAlternative: '代替場所を適用', undo: '元に戻す',
    signalTitle: '広告性の言及を除外した最近のローカル情報', signalDisclosure: '原文、投稿者、外部URLを表示しない集計デモです。',
    viewPlace: '場所を見る', noResults: '検索結果がありません', reset: 'デモを初期化', settings: '設定', close: '閉じる',
    notifications: '通知', mainNavigation: 'メインメニュー', categoryFilter: 'カテゴリーフィルター',
    mapAlt: 'ソウル鍾路区のデモ地図背景', pmModerate: 'PM10デモ: 普通', details: '詳細を見る',
    clearSearch: '検索を消去', sortResults: '検索結果を並べ替え', explore: '探索',
    forecastContext: '地域情報 · デモ天気', fourSlotRhythm: '4枠の旅程',
    openSlot: '空き枠', noCandidate: '候補がない場合、場所を作り上げません。',
    governedAggregate: '管理された集計', quiet: '静か', active: '活発', organic: '自然な言及',
    filteredNote: '広告性・重複の言及を除外しました。', privacyNote: '原文や投稿者情報は表示しません。',
    textFirst: 'テキスト優先の代替', transparentEvidence: '透明な根拠', reason: 'おすすめ理由', gallery: 'ギャラリー',
    languageLabel: '言語', regionLabel: '地域', evidenceFirst: '根拠優先デモ',
    demoBoundaryNote: '決定可能なデモデータのみを使用し、実際のLALA運用結果とは主張しません。',
    noLocationPermission: 'デモでは位置情報を要求せず、鍾路区のデモ地域から開始します。',
    back: '戻る', coverageUnavailable: 'この地域のデモデータはまだありません。',
    coverageBody: '全国の地域選択は可能ですが、他地域にソウルの場所を代用表示しません。',
    chooseDemoRegion: '鍾路区デモを見る',
  },
  'zh-CN': {
    search: '搜索', map: '地图', plan: '行程', signals: '本地动态',
    demoData: '演示数据', currentRegion: '当前地区', change: '更改',
    all: '全部', culture: '文化', food: '美食', local: '本地',
    tripTitle: '您计划怎样的旅行？', tripBody: '请选择最符合今天探索方式的选项。',
    spontaneous: '随性旅行', planned: '计划旅行', localFocused: '深入本地', next: '下一步',
    languageTitle: '选择显示语言', languageBody: '主要界面将使用所选语言。',
    locationTitle: '设置推荐地区', locationBody: '无需位置权限，也可直接选择全国地区。',
    currentLocation: '使用当前位置', manualRegion: '选择地区', start: '开始使用 LALA',
    searchPlaceholder: '搜索地点或地区', distance: '距离', popular: '推荐',
    recent: '最近搜索', evidence: '推荐理由', updated: '数据时间', source: '来源',
    addPlan: '加入行程', saved: '已保存', save: '保存', route: '查看路线',
    docent: 'AI 导览', textMode: '文本模式', audioUnavailable: '演示版未启用语音',
    generateWithGemini: '使用 Gemini 生成导览', checkingGemini: '正在检查服务器设置', generatingDocent: '正在根据依据生成',
    liveDocentReady: '服务器生成的导览', liveDocentUnavailable: '服务器未配置 Secret，继续显示默认导览。',
    morning: '上午', lunch: '午餐', afternoon: '下午', evening: '晚上', estimated: '预计',
    intervention: '当前地区预计有阵雨，建议选择附近的室内地点。',
    keepPlan: '保留原行程', applyAlternative: '使用替代地点', undo: '撤销',
    signalTitle: '过滤商业内容后的近期本地动态', signalDisclosure: '本演示仅显示汇总结果，不显示原文、作者或外部链接。',
    viewPlace: '查看地点', noResults: '没有搜索结果', reset: '重置演示', settings: '设置', close: '关闭',
    notifications: '通知', mainNavigation: '主菜单', categoryFilter: '分类筛选',
    mapAlt: '首尔钟路区演示地图背景', pmModerate: 'PM10 演示：一般', details: '查看详情',
    clearSearch: '清除搜索', sortResults: '搜索结果排序', explore: '探索',
    forecastContext: '本地信号 · 演示天气', fourSlotRhythm: '四时段行程',
    openSlot: '空闲时段', noCandidate: '没有候选地点时不会虚构地点。',
    governedAggregate: '受控汇总', quiet: '安静', active: '活跃', organic: '自然提及',
    filteredNote: '已过滤商业和重复内容。', privacyNote: '不显示原文和作者身份。',
    textFirst: '文本优先替代', transparentEvidence: '透明依据', reason: '推荐理由', gallery: '图库',
    languageLabel: '语言', regionLabel: '地区', evidenceFirst: '依据优先演示',
    demoBoundaryNote: '仅使用确定性的演示数据，不将其声称为 LALA 实际运行结果。',
    noLocationPermission: '演示版不会请求真实位置权限，并从钟路区演示地区开始。',
    back: '返回', coverageUnavailable: '该地区的演示数据尚未准备好。',
    coverageBody: '可以选择全国地区，但不会用首尔地点冒充其他地区的数据。',
    chooseDemoRegion: '查看钟路区演示',
  },
  'zh-TW': {
    search: '搜尋', map: '地圖', plan: '行程', signals: '在地動態',
    demoData: '示範資料', currentRegion: '目前地區', change: '變更',
    all: '全部', culture: '文化', food: '美食', local: '在地',
    tripTitle: '您計畫怎樣的旅行？', tripBody: '請選擇最符合今天探索方式的選項。',
    spontaneous: '隨性旅行', planned: '計畫旅行', localFocused: '深入在地', next: '下一步',
    languageTitle: '選擇顯示語言', languageBody: '主要介面將使用所選語言。',
    locationTitle: '設定推薦地區', locationBody: '無需位置權限，也可直接選擇全國地區。',
    currentLocation: '使用目前位置', manualRegion: '選擇地區', start: '開始使用 LALA',
    searchPlaceholder: '搜尋地點或地區', distance: '距離', popular: '推薦',
    recent: '最近搜尋', evidence: '推薦理由', updated: '資料時間', source: '來源',
    addPlan: '加入行程', saved: '已儲存', save: '儲存', route: '查看路線',
    docent: 'AI 導覽', textMode: '文字模式', audioUnavailable: '示範版未啟用語音',
    generateWithGemini: '使用 Gemini 產生導覽', checkingGemini: '正在檢查伺服器設定', generatingDocent: '正在依據資料產生',
    liveDocentReady: '伺服器產生的導覽', liveDocentUnavailable: '伺服器未設定 Secret，繼續顯示預設導覽。',
    morning: '上午', lunch: '午餐', afternoon: '下午', evening: '晚上', estimated: '預估',
    intervention: '目前地區預計有陣雨，建議選擇附近的室內地點。',
    keepPlan: '保留原行程', applyAlternative: '使用替代地點', undo: '復原',
    signalTitle: '過濾商業內容後的近期在地動態', signalDisclosure: '本示範僅顯示彙整結果，不顯示原文、作者或外部連結。',
    viewPlace: '查看地點', noResults: '沒有搜尋結果', reset: '重設示範', settings: '設定', close: '關閉',
    notifications: '通知', mainNavigation: '主選單', categoryFilter: '分類篩選',
    mapAlt: '首爾鐘路區示範地圖背景', pmModerate: 'PM10 示範：普通', details: '查看詳情',
    clearSearch: '清除搜尋', sortResults: '搜尋結果排序', explore: '探索',
    forecastContext: '在地訊號 · 示範天氣', fourSlotRhythm: '四時段行程',
    openSlot: '空白時段', noCandidate: '沒有候選地點時不會虛構地點。',
    governedAggregate: '受控彙整', quiet: '安靜', active: '活躍', organic: '自然提及',
    filteredNote: '已過濾商業與重複內容。', privacyNote: '不顯示原文與作者身分。',
    textFirst: '文字優先替代', transparentEvidence: '透明依據', reason: '推薦理由', gallery: '圖庫',
    languageLabel: '語言', regionLabel: '地區', evidenceFirst: '依據優先示範',
    demoBoundaryNote: '僅使用確定性的示範資料，不將其宣稱為 LALA 實際運行結果。',
    noLocationPermission: '示範版不會要求真實位置權限，並從鐘路區示範地區開始。',
    back: '返回', coverageUnavailable: '此地區的示範資料尚未準備好。',
    coverageBody: '可以選擇全國地區，但不會用首爾地點冒充其他地區的資料。',
    chooseDemoRegion: '查看鐘路區示範',
  },
};

export function localize(text: LocalizedText, language: Language): { value: string; fallback: boolean } {
  const value = text[language];
  if (value) return { value, fallback: false };
  return { value: text.en, fallback: language !== 'en' };
}
